IntersectMBO/cc-portal

LICENSE
README.md

- Add license file
- Change base readme, slight reorganise

docs: add license file and tweak base readme

---

.github/workflows/merge.yaml

add comment

---

.github/workflows/merge.yaml

add microservice in pr comment

---

frontend/package-lock.json

Reverts IntersectMBO/cc-portal#264

Revert "chore: Update packages"

---

frontend/Dockerfile

- Fix deployment issues caused by not setting environment variables.

fix: docker env issue

---

frontend/src/components/atoms/OutlinedLightButton.tsx
frontend/src/components/molecules/TableDivider.tsx
frontend/src/components/organisms/VotesTable/VotesTableRow.tsx

fix: vote table row responsiveness

---

.github/workflows/merge.yaml
.github/workflows/pr.yaml
frontend/Dockerfile

test w/ individual service failing

---

.github/workflows/merge.yaml
.github/workflows/pr.yaml

fail fast disable & tag in pr

---

ipfs-service/example.env
ipfs-service/package-lock.json
ipfs-service/package.json
ipfs-service/src/app.module.ts
ipfs-service/src/app.service.ts
ipfs-service/src/bullmq/bullmq.module.ts
ipfs-service/src/constants/bullmq.constants.ts
ipfs-service/src/main.ts
ipfs-service/src/queues/processors/provide-to-dht.processor.ts
ipfs-service/src/queues/producers/provide-to-dht.producer.ts
ipfs-service/src/util/logger-factory.ts

Added a dht queue for publishing cid to dht

feat: dht-queue

---

frontend/src/constants/paths.ts

chore: change guides btn link

---

.github/workflows/pr.yaml

refactor: .env vars

---

frontend/src/components/molecules/GovernanceActionsSorting.tsx
frontend/src/components/organisms/Modals/SignInModal.tsx
frontend/src/components/organisms/Modals/SignUpModal.tsx

fix: Remove comments for selector ids

---

frontend/src/context/usersnap.tsx

fix: usersnap showing all on path change

---

frontend/src/context/usersnap.tsx

fix: Usersnap query params issue

---

.github/workflows/merge.yaml

refactor:staging-branch

---

backend/migrations/1727279527027-add-indexes-to-searchable-columns.ts
backend/src/governance/entities/gov-action-proposal.entity.ts
backend/src/governance/entities/vote.entity.ts
backend/src/users/entities/role.entity.ts
backend/src/users/entities/user.entity.ts

-  Added indexes to searchable columns in the database

fix: add indexes to searchable columns

---

backend/migrations/1728062638428-users-relations.ts
backend/postman/CC Portal develop.postman_collection.json
backend/src/governance/entities/rationale.entity.ts
backend/src/governance/entities/vote.entity.ts
backend/src/users/api/request/remove-user.request.ts
backend/src/users/api/users.controller.ts
backend/src/users/entities/hotaddress.entity.ts
backend/src/users/entities/user.entity.ts
backend/src/users/facade/users.facade.ts
backend/src/users/services/users.service.ts

- Added hard delete user ability

feat: hard delete user

---

backend/src/users/util/pagination/user-pagination.config.ts

- Sorted users by name in ascending order

fix: sorting users

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_idea.yml

- Chore: update issue templates to add new issues to prohects

chore: update issue template to add issues to projects

---

backend/migrations/1729504273717-vote-metadata-url.ts
backend/src/governance/api/response/vote.response.ts
backend/src/governance/dto/vote.dto.ts
backend/src/governance/entities/vote.entity.ts
backend/src/governance/mapper/governance-mapper.ts
worker-service/src/common/common-service.ts
worker-service/src/governance/dto/vote.request.ts
worker-service/src/governance/entities/vote.entity.ts
worker-service/src/governance/mapper/vote.mapper.ts
worker-service/src/governance/services/gov-action-proposal.service.ts
worker-service/src/governance/services/vote.service.ts
worker-service/src/governance/sql/get-votes.sql

fix: sync-votes

---

frontend/messages/de.json
frontend/messages/en.json
frontend/src/components/atoms/Link.tsx
frontend/src/components/organisms/Constitution/Constitution.tsx
frontend/src/components/organisms/Constitution/ConstitutionSidebar.tsx
frontend/src/components/organisms/Constitution/MDXComponents.tsx
frontend/src/components/organisms/Constitution/TOCAccordion.tsx
frontend/src/components/organisms/Constitution/TOCLink.tsx
frontend/src/components/organisms/LatestUpdates.tsx
frontend/src/components/organisms/Modals/PreviewReasoningModal.tsx
frontend/src/components/organisms/TopNavigation/TopNav.tsx
frontend/src/components/organisms/VotesTable/VotesTableRow.tsx
frontend/src/components/organisms/types.ts
frontend/src/lib/requests/getConstitution.ts
frontend/src/lib/requests/types.ts

added rationale link on latest updates table

---

frontend/src/components/organisms/Constitution/Constitution.tsx
frontend/src/components/organisms/Constitution/MDXComponents.tsx
frontend/src/components/organisms/Constitution/TOCAccordion.tsx
frontend/src/components/organisms/Constitution/TOCLink.tsx
frontend/src/components/organisms/Constitution/TOCNested.tsx
frontend/src/lib/requests/getConstitution.ts
frontend/src/theme.ts

fix: navigation side bar visual known issues

---

backend/src/users/api/request/update-user.request.ts

- Enabled character | (pipe) in the user name

fix: change user name validation

---

ipfs-service/src/bullmq/bullmq.module.ts

- Added option reconnect on error

fix: bullmq redis reconnect

---

backend/migrations/1731932955459-limit-users-name-field.ts
backend/src/users/api/request/update-user.request.ts
backend/src/users/entities/user.entity.ts

- The user's name is limited to 64 characters.

fix: limit for users name

---

ipfs-service/src/app.service.ts

…rensport…" (#485)
This reverts commit 814649572e984ea6ac6fbd9ee8d8d6040b02394e.

Revert "fix/disable-ipfs-circuit-relay: disabled ipfs circuit relay"

---

frontend/src/components/organisms/NotFound.tsx

fix: Fixed not found page height

---

frontend/src/app/[locale]/verify/register/page.tsx
frontend/src/components/organisms/TopNavigation/TopNav.tsx

fix: Sign up modal always displayed if there is no username

---

frontend/src/app/[locale]/layout.tsx

feat: Added Matomo script to App

---

frontend/src/components/organisms/Constitution/Constitution.tsx
frontend/src/components/organisms/Constitution/MDXComponents.tsx

fix: Fixed VH button and add new member button positon

---

frontend/src/components/organisms/Constitution/MDXComponents.tsx

chore: small fix

---

docker-compose.yaml

Ipfs-volume

---

frontend/messages/de.json
frontend/messages/en.json
frontend/src/app/[locale]/voting-updates/page.tsx
frontend/src/components/organisms/MembersCard/MembersCard.tsx
frontend/src/components/organisms/MyActions.tsx
frontend/src/components/organisms/VotesTable/VotesTableRow.tsx
frontend/src/components/organisms/VotingUpdates.tsx
frontend/src/components/organisms/index.ts
frontend/src/constants/governanceAction/filters.ts
frontend/src/constants/governanceAction/sorting.ts
frontend/src/constants/navItems.ts
frontend/src/constants/paths.ts
frontend/src/lib/api.ts
frontend/src/middleware.ts

feat: Changed naming of latest updates to voting updates

---

frontend/src/app/[locale]/layout.tsx

chore: removed matomo

---

frontend/src/app/[locale]/layout.tsx

chore: added matomo

---

backend/src/s3/client/s3client.ts

fix: minio-region

---

frontend/src/components/organisms/UsersList/UsersListItem.tsx
frontend/src/lib/api.ts

feat: Paginate 7 members

---

frontend/src/components/molecules/UserProfileButton.tsx

feat: Added border to header dropdown menu

---

frontend/src/components/organisms/VotesTable/VotesTableRow.tsx

feat: Displayed full title on hover for truncated GA titles

---

frontend/src/components/atoms/MultipleSelect.tsx
frontend/src/lib/api.ts

feat: Added missing indicator

---

frontend/src/components/molecules/GovernanceActionsFilters.tsx
frontend/src/components/molecules/UserProfileButton.tsx

feat: Replaced border of dropdown with shadow

---

.gitignore

refactor .gitignore

---

frontend/messages/de.json
frontend/messages/en.json
frontend/src/components/atoms/OutlinedLightButton.tsx
frontend/src/components/organisms/Modals/PreviewReasoningModal.tsx

feat: Reordered sections in show more modal, Added title for Abstract

---

frontend/src/components/organisms/Modals/PreviewReasoningModal.tsx

feat: Open new tab when rationale is clicked

---

frontend/src/lib/requests/getConstitution.ts

fix: Fixed Constitution sidebar

---

ipfs-service/src/app.service.ts

- Disabled circuit raley transport and 
- Added announce addresses

refactor: ipfs service ibp2p

---

frontend/src/components/organisms/Hero/HeroActions.tsx

fix: Fixed Icon size

---

frontend/src/app/[locale]/page.tsx

fix: Fixed redirection problems

---

frontend/src/components/organisms/Modals/SignUpModal.tsx
frontend/src/lib/api.ts
frontend/src/lib/axiosInstance.js

feat: Displayed error msg for hot address from BE response

---

frontend/messages/en.json
frontend/src/components/atoms/UploadFileButton.tsx
frontend/src/components/organisms/Modals/SignUpModal.tsx
frontend/src/lib/api.ts

feat: Added Button for removing User profile photo

---

frontend/src/components/atoms/VotePill.tsx
frontend/src/components/organisms/Modals/PreviewReasoningModal.tsx
frontend/src/components/organisms/VotesTable/VotesTableRow.tsx
frontend/src/lib/utils/string.ts

feat: Changed voting labels

---

frontend/public/icons/Close.svg
frontend/src/components/atoms/UploadFileButton.tsx
frontend/src/components/molecules/UserProfileButton.tsx
frontend/src/components/organisms/Modals/SignUpModal.tsx

feat: Updated Upload img button

---

frontend/src/components/atoms/UploadFileButton.tsx

fix: Fixed Profile image name overflow case

---

frontend/src/components/molecules/UserProfileButton.tsx

chore: Added disable autofocus on profile menu

---

frontend/src/constants/governanceAction/filters.ts

feat: Updated Votes filter component

---

frontend/src/constants/governanceAction/filters.ts

chore: Uppercase to lowercase

---

backend/src/constitution/api/constitution.controller.ts
backend/src/users/api/users.controller.ts
worker-service/package-lock.json
worker-service/package.json
worker-service/src/bullmq/bullmq.module.ts

- minor changes in the swagger docs

fix: swagger docs

---

frontend/src/components/organisms/Constitution/MDXComponents.tsx
frontend/src/components/organisms/Constitution/TOCLink.tsx

fix: Fixed selecting constitution titles

---

frontend/src/components/organisms/Constitution/Constitution.tsx

fix: Fixed mobile drawer issue

---

frontend/src/components/atoms/Link.tsx
frontend/src/components/organisms/TopNavigation/TopNav.tsx
frontend/src/constants/navItems.ts
frontend/src/constants/paths.ts

feat: Added Elections external link in TopNav
